Add packages by tracking number
bachya/py17track pull request #54
Opened 2021-04-05 11:33 UTC by ofalvai

**Describe what the PR does:**

Adds a new method (`add_packages`) to add one or more packages to track by their tracking number.

Unfortunately, I couldn't find a way to add a friendly name to each new package. The API method that adds a friendly name (`SetTrackRemark`) expects an internal ID, not the tracking number itself. This internal ID isn't returned when adding a new package, only when getting all tracked packages.

@bachya what do you think, would it make sense to create a method that calls `packages()` first to get that internal ID, and then sets a friendly name for that ID?

**Does this fix a specific issue?**

Fixes https://github.com/bachya/py17track/issues/53
  
**Checklist:**

- [X] Confirm that one or more new tests are written for the new functionality.
- [X] Update `README.md` with any new documentation.
- [X] Add yourself to `AUTHORS.md`.

2021-04-06 16:54 UTC, bachya commented
>@bachya what do you think, would it make sense to create a method that calls packages() first to get that internal ID, and then sets a friendly name for that ID?

This isn't the worst thing, but we should only do it if the user provides a friendly name – perhaps a `friendly_name` kwarg and if it's provided, we do the flow you suggest?

2021-04-18 17:18 UTC, ofalvai commented
@bachya Done, please take a look :)

2021-04-19 17:53 UTC, bachya requested changes

2021-04-19 17:53 UTC, bachya commented on py17track/profile.py
> +                "id": package.get("FTrackInfoId"),
You define `id` as a required attribute of the `Package` class, but this implies that the value could be `None`. Is that expected? Either way is ultimately fine, but we should be consistent (i.e., if it's expected, access it directly; if it can be `None`, make it an optional attribute).

2021-04-19 17:53 UTC, bachya commented on py17track/profile.py
> +            return False
We shouldn't swallow an unsuccessful response here. If we could get an `HTTP 2xx` response with a non-0 `Code`, we should raise a `RequestError`.

2021-04-19 17:53 UTC, bachya commented on py17track/profile.py
> +            return False
This would eliminate the need for returning a `bool`, as well – if an exception isn't raised, we can assume the request was successful.

2021-04-19 17:53 UTC, bachya commented on py17track/profile.py
> +        if friendly_name is not None:
We can avoid nesting here by reversing things into a guard clause:

```
if not friendly_name:
  return
```

2021-04-19 17:53 UTC, bachya commented on py17track/profile.py
> +                filter(lambda p: (p.tracking_number == tracking_number), packages), None
Using filter with a lambda feels very un-Pythonic. How about:

```python
try:
  new_package = next(p for p in packages if p.tracking_number == tracking_number)
except StopIteration:
  # Raise an exception? Return?
```

2021-04-19 17:53 UTC, bachya commented on py17track/profile.py
> +            if new_package is not None:
Reverse this to avoid deep nesting.

2021-04-19 17:53 UTC, bachya commented on py17track/profile.py
> +                if success is False:
Don't swallow errors.

2021-04-19 17:53 UTC, bachya commented on py17track/profile.py
> +        if remark_resp.get("Code") != 0:
Don't swallow errors.

2021-04-24 14:51 UTC, ofalvai commented on py17track/profile.py
> +                "id": package.get("FTrackInfoId"),
Good catch, I chose the optional ID.

2021-04-24 14:56 UTC, ofalvai commented
Thanks @bachya for the detailed review comments. I tried to fix all of them, but let me know if something is still not right (as you might have guessed, I'm not that familiar with the Python world 😁).
I also leave it to you to decide the fate of that cyclomatic complexity warning.

2021-04-24 17:27 UTC, bachya commented on py17track/package.py
> +    id: Optional[str] = attr.ib(default=None)
Small nit: let's group the `Optional` attributes together.

2021-04-24 17:27 UTC, bachya commented
Looking good overall! One little comment, plus you need to make sure you write tests to cover new functionality. Don't worry about the Code Climate warning; I'm not concerned.

2021-04-25 06:53 UTC, ofalvai commented
Done, code coverage is 100% again :)

2021-04-28 18:43 UTC, bachya approved these changes
Good to merge once CI passes!

2021-04-29 00:15 UTC, merged